// utils/seeder.js — Seed sample courses and a test user
require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Course = require('../models/Course');
const User = require('../models/User');

const sampleCourses = [
  {
    title: 'The Complete React Developer Course',
    description: 'Master React from zero to hero. Hooks, Redux, React Router, and more.',
    instructor: 'Priya Sharma',
    category: 'Web Development',
    tags: ['React', 'JavaScript', 'Frontend', 'Hooks', 'Redux'],
    level: 'intermediate',
    duration: '38 hours',
    totalLessons: 95,
    price: 0,
    rating: 4.8,
    enrolledCount: 12400,
    isFeatured: true,
    thumbnail: 'https://img.icons8.com/color/96/react-native.png',
  },
  {
    title: 'Python for Data Science & Machine Learning',
    description: 'Complete bootcamp: NumPy, Pandas, Matplotlib, Scikit-Learn, and real ML projects.',
    instructor: 'Arjun Mehta',
    category: 'Data Science',
    tags: ['Python', 'Data Science', 'Machine Learning', 'Pandas', 'NumPy'],
    level: 'beginner',
    duration: '42 hours',
    totalLessons: 110,
    price: 0,
    rating: 4.9,
    enrolledCount: 18900,
    isFeatured: true,
    thumbnail: 'https://img.icons8.com/color/96/python.png',
  },
  {
    title: 'Deep Learning & Neural Networks with TensorFlow',
    description: 'Build CNNs, RNNs, GANs and deploy AI models using TensorFlow 2.x.',
    instructor: 'Dr. Kavya Nair',
    category: 'AI/ML',
    tags: ['Deep Learning', 'TensorFlow', 'Neural Networks', 'AI', 'Python'],
    level: 'advanced',
    duration: '50 hours',
    totalLessons: 125,
    price: 0,
    rating: 4.7,
    enrolledCount: 8700,
    isFeatured: true,
    thumbnail: 'https://img.icons8.com/color/96/tensorflow.png',
  },
  {
    title: 'Ethical Hacking & Penetration Testing',
    description: 'Hands-on cybersecurity: network hacking, system exploitation, and web app pentesting.',
    instructor: 'Rohan Iyer',
    category: 'Cybersecurity',
    tags: ['Cybersecurity', 'Hacking', 'Network Security', 'Kali Linux', 'Pentesting'],
    level: 'intermediate',
    duration: '30 hours',
    totalLessons: 70,
    price: 0,
    rating: 4.6,
    enrolledCount: 5400,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/security-shield-green.png',
  },
  {
    title: 'Full Stack MERN Developer Bootcamp',
    description: 'Build 3 full-stack projects: MongoDB, Express, React, Node.js from scratch.',
    instructor: 'Sneha Verma',
    category: 'Web Development',
    tags: ['MERN', 'MongoDB', 'Express', 'React', 'Node.js', 'Full Stack'],
    level: 'intermediate',
    duration: '55 hours',
    totalLessons: 140,
    price: 0,
    rating: 4.8,
    enrolledCount: 14200,
    isFeatured: true,
    thumbnail: 'https://img.icons8.com/color/96/nodejs.png',
  },
  {
    title: 'AWS Cloud Practitioner Certification',
    description: 'Prepare for AWS CLF-C02 exam: EC2, S3, Lambda, IAM, and cloud fundamentals.',
    instructor: 'Vikram Rao',
    category: 'Cloud Computing',
    tags: ['AWS', 'Cloud Computing', 'Certification', 'DevOps', 'Infrastructure'],
    level: 'beginner',
    duration: '20 hours',
    totalLessons: 55,
    price: 0,
    rating: 4.5,
    enrolledCount: 9800,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/amazon-web-services.png',
  },
  {
    title: 'Flutter & Dart — Complete Mobile App Development',
    description: 'Build iOS & Android apps with Flutter. State management, APIs, and Firebase.',
    instructor: 'Anjali Gupta',
    category: 'Mobile Development',
    tags: ['Flutter', 'Dart', 'Mobile Development', 'iOS', 'Android', 'Firebase'],
    level: 'beginner',
    duration: '35 hours',
    totalLessons: 85,
    price: 0,
    rating: 4.7,
    enrolledCount: 7600,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/flutter.png',
  },
  {
    title: 'SQL & Database Design Masterclass',
    description: 'Master SQL queries, joins, stored procedures, indexing, and database design patterns.',
    instructor: 'Kiran Desai',
    category: 'Database',
    tags: ['SQL', 'Database', 'MySQL', 'PostgreSQL', 'Database Design'],
    level: 'beginner',
    duration: '22 hours',
    totalLessons: 58,
    price: 0,
    rating: 4.6,
    enrolledCount: 11300,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/sql.png',
  },
  {
    title: 'Natural Language Processing with Python',
    description: 'Build NLP models: text classification, sentiment analysis, chatbots with NLTK & spaCy.',
    instructor: 'Dr. Meera Pillai',
    category: 'AI/ML',
    tags: ['NLP', 'Python', 'AI', 'Machine Learning', 'spaCy', 'NLTK'],
    level: 'advanced',
    duration: '28 hours',
    totalLessons: 68,
    price: 0,
    rating: 4.5,
    enrolledCount: 4200,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/artificial-intelligence.png',
  },
  {
    title: 'Docker & Kubernetes for DevOps Engineers',
    description: 'Containerization, orchestration, CI/CD pipelines, Helm charts, and microservices.',
    instructor: 'Suresh Patel',
    category: 'DevOps',
    tags: ['Docker', 'Kubernetes', 'DevOps', 'CI/CD', 'Containers', 'Cloud'],
    level: 'intermediate',
    duration: '32 hours',
    totalLessons: 80,
    price: 0,
    rating: 4.7,
    enrolledCount: 6500,
    isFeatured: true,
    thumbnail: 'https://img.icons8.com/color/96/docker.png',
  },
  {
    title: 'UI/UX Design with Figma — Zero to Pro',
    description: 'Design stunning interfaces: wireframes, prototypes, design systems using Figma.',
    instructor: 'Ritu Singh',
    category: 'UI/UX Design',
    tags: ['Figma', 'UI Design', 'UX Design', 'Prototyping', 'Design Systems'],
    level: 'beginner',
    duration: '26 hours',
    totalLessons: 65,
    price: 0,
    rating: 4.6,
    enrolledCount: 8900,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/figma.png',
  },
  {
    title: 'Data Structures & Algorithms in Python',
    description: 'Ace coding interviews: arrays, trees, graphs, dynamic programming explained visually.',
    instructor: 'Prof. Arun Kumar',
    category: 'Programming',
    tags: ['DSA', 'Algorithms', 'Python', 'Interview Prep', 'Problem Solving'],
    level: 'intermediate',
    duration: '40 hours',
    totalLessons: 100,
    price: 0,
    rating: 4.9,
    enrolledCount: 22100,
    isFeatured: true,
    thumbnail: 'https://img.icons8.com/color/96/code.png',
  },
  {
    title: 'JavaScript — The Complete Guide (ES6+ & Beyond)',
    description: 'Comprehensive JS: closures, promises, async/await, OOP, and modern patterns.',
    instructor: 'Nidhi Tiwari',
    category: 'Web Development',
    tags: ['JavaScript', 'ES6', 'Web Development', 'Frontend', 'Node.js'],
    level: 'beginner',
    duration: '45 hours',
    totalLessons: 115,
    price: 0,
    rating: 4.8,
    enrolledCount: 19500,
    isFeatured: true,
    thumbnail: 'https://img.icons8.com/color/96/javascript.png',
  },
  {
    title: 'Data Analytics with Power BI',
    description: 'Build professional dashboards, DAX formulas, data modeling in Power BI Desktop.',
    instructor: 'Rahul Bose',
    category: 'Data Science',
    tags: ['Power BI', 'Data Analytics', 'Dashboard', 'Business Intelligence', 'DAX'],
    level: 'beginner',
    duration: '18 hours',
    totalLessons: 48,
    price: 0,
    rating: 4.5,
    enrolledCount: 7200,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/power-bi.png',
  },
  {
    title: 'Cybersecurity Fundamentals for Beginners',
    description: 'Introduction to cybersecurity: CIA triad, firewalls, VPNs, and basic threat analysis.',
    instructor: 'Pooja Jain',
    category: 'Cybersecurity',
    tags: ['Cybersecurity', 'Network Security', 'Firewall', 'Beginner', 'Security'],
    level: 'beginner',
    duration: '15 hours',
    totalLessons: 40,
    price: 0,
    rating: 4.4,
    enrolledCount: 4800,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/cyber-security.png',
  },
  {
    title: 'GraphQL API Development with Node.js',
    description: 'Build GraphQL APIs: schemas, resolvers, subscriptions, authentication with Apollo Server.',
    instructor: 'Manish Kapoor',
    category: 'Web Development',
    tags: ['GraphQL', 'Node.js', 'API', 'Apollo', 'Backend', 'Full Stack'],
    level: 'advanced',
    duration: '24 hours',
    totalLessons: 60,
    price: 0,
    rating: 4.6,
    enrolledCount: 3100,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/graphql.png',
  },
  {
    title: 'Computer Vision with OpenCV & Python',
    description: 'Object detection, face recognition, image segmentation using OpenCV and YOLO.',
    instructor: 'Dr. Ananya Sen',
    category: 'AI/ML',
    tags: ['Computer Vision', 'OpenCV', 'Python', 'AI', 'YOLO', 'Deep Learning'],
    level: 'intermediate',
    duration: '30 hours',
    totalLessons: 75,
    price: 0,
    rating: 4.6,
    enrolledCount: 5900,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/camera.png',
  },
  {
    title: 'Git & GitHub — Version Control Masterclass',
    description: 'Master Git: branching, merging, rebasing, pull requests, and GitHub workflow.',
    instructor: 'Amitabh Roy',
    category: 'Programming',
    tags: ['Git', 'GitHub', 'Version Control', 'DevOps', 'Collaboration'],
    level: 'beginner',
    duration: '10 hours',
    totalLessons: 30,
    price: 0,
    rating: 4.7,
    enrolledCount: 15600,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/git.png',
  },
  {
    title: 'Google Cloud Professional Data Engineer',
    description: 'BigQuery, Dataflow, Pub/Sub, ML APIs — prep for GCP Professional Data Engineer exam.',
    instructor: 'Latha Krishnan',
    category: 'Cloud Computing',
    tags: ['Google Cloud', 'BigQuery', 'Data Engineering', 'Cloud Computing', 'GCP'],
    level: 'advanced',
    duration: '36 hours',
    totalLessons: 90,
    price: 0,
    rating: 4.5,
    enrolledCount: 2800,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/google-cloud.png',
  },
  {
    title: 'React Native — Build Mobile Apps with React',
    description: 'Build cross-platform mobile apps using React Native, Expo, and native APIs.',
    instructor: 'Chirag Shah',
    category: 'Mobile Development',
    tags: ['React Native', 'React', 'Mobile Development', 'Expo', 'JavaScript'],
    level: 'intermediate',
    duration: '28 hours',
    totalLessons: 70,
    price: 0,
    rating: 4.6,
    enrolledCount: 6100,
    isFeatured: false,
    thumbnail: 'https://img.icons8.com/color/96/react-native.png',
  },
];

const sampleUser = {
  name: 'Seethaka Demo',
  email: 'demo@olcrp.com',
  password: 'demo123',
  skills: ['JavaScript', 'Python', 'React'],
  interests: ['Web Development', 'Data Science', 'AI/ML'],
  experienceLevel: 'intermediate',
};

const seedDB = async () => {
  await connectDB();

  console.log('Clearing old data...');
  await Course.deleteMany();
  await User.deleteMany({ email: sampleUser.email });

  console.log('Inserting 20 sample courses...');
  await Course.insertMany(sampleCourses);

  console.log('Creating demo user...');
  await User.create(sampleUser);

  console.log('✅ Seeding complete!');
  console.log(`Demo login → email: ${sampleUser.email} | password: ${sampleUser.password}`);
  process.exit();
};

seedDB().catch((err) => {
  console.error('Seeder error:', err);
  process.exit(1);
});